[open] - without making default

diff --git a/digikamctl b/digikamctl
--- a/digikamctl
+++ b/digikamctl
@@ -18,7 +18,7 @@ REPO="${HOME}/Pictures/DigiKams"
 # How did you install digikam
 # 1 = digikam was installed via package manager like dnf
 # 2 = digikam was installed via flatpak
-EDITION=2
+EDITION=1
 
 # -------------------------------------------------------
 # You don't have to change anything else below this line.
@@ -86,18 +86,18 @@ function use_lib() { #{{{
 
 function open_lib() { #{{{
     # Activating library if it wasn't
-    if [ "${USEDDKL}" != "${1}" ]; then
-        use_lib "${1}"
-        if [ $? != 0 ]; then
-            echo "[ERROR]: Since we could not activate '${1}' library, we can not open it."
-            return 1
-        fi
-    fi
+    # if [ "${USEDDKL}" != "${1}" ]; then
+    #     use_lib "${1}"
+    #     if [ $? != 0 ]; then
+    #         echo "[ERROR]: Since we could not activate '${1}' library, we can not open it."
+    #         return 1
+    #     fi
+    # fi
     echo "Opening '${1}' library.."
     # Digikam commands (1:pkg, 2:flatpak)
     if [ "${EDITION}" -eq 1 ]; then
         cd "${_TMPDIR}"
-        nohup /usr/bin/digikam &
+        nohup "/usr/bin/digikam" --database-directory "${REPO}/${1}/Database/" --config "${REPO}/${1}/digikamrc" &
         cd "${CDIR}"
     elif [ "${EDITION}" -eq 2 ]; then
         cd "${_TMPDIR}"
